import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import seaborn as sns


def plot_hamiltonian_expval_heatmap(
    data: np.ndarray, xlabel: str = None, ylabel: str = None, title: str = None
) -> None:
    """Generates a heatmap plot 
    
    Args:
        data (np.ndarray): Plot data (Hamiltonian expectation value).
        xlabel (str, optional): x-axis label. Defaults to None.
        ylabel (str, optional): y-axis label. Defaults to None.
        title (str, optional): Plot title. Defaults to None.
    """

    _, ax = plt.subplots()

    sns.heatmap(data=data)
    ax.set_xlabel(r"$\theta_0$" if xlabel is None else xlabel)
    ax.set_ylabel(r"$\theta_1$" if ylabel is None else ylabel)
    ax.set_title("Hamiltonian expectation value heatmap" if title is None else title)

    plt.show()


def plot_hamiltonian_expval_surface(
    x: np.ndarray,
    y: np.ndarray,
    z: np.ndarray,
    xlabel: str = None,
    ylabel: str = None,
    title: str = None,
) -> go.Figure:
    """Generates a 3D interactive plot
    of the sufarce generated by 
    hamiltonian expectation value.

    Args:
        x (np.ndarray): Parameter 1 values.
        y (np.ndarray): Parameter 2 values.
        z (np.ndarray): Hamiltonian expectation value data.
        xlabel (str, optional): x-axis label. Defaults to None.
        ylabel (str, optional): y-axis label. Defaults to None.
        title (str, optional): Plot title. Defaults to None.

    Returns: An object of type go.Figure.
    """

    data = go.Surface(x=x, y=y, z=z)
    fig = go.Figure(data=data)
    # Adding annotations to handle 3D surfaces bug with LaTeX.
    annotations = [
        dict(x=3.14, y=7.0, z=-0.03, text=r"$\theta_0$", showarrow=False),
        dict(x=7.0, y=3.14, z=-0.03, text=r"$\theta_1$", showarrow=False),
        dict(x=7.0, y=0, z=0, text=r"$\langle H \rangle$", showarrow=False)
    ]
    fig.update_layout(
        title_text=(
            "Hamiltonian expectation value landscape" if title is None else title
        ),
        scene=dict(
            xaxis=dict(title="x" if xlabel is None else xlabel),
            yaxis=dict(title="y" if ylabel is None else ylabel),
            zaxis=dict(title="z"),
            annotations=annotations
        )
    )

    return fig


def plot_static_efficient_frontier(
    df_efficient_frontier: pd.DataFrame, df_portfolios: pd.DataFrame = None
) -> None:
    """Creates a static plot of the efficient frontier.
    
    Args:
        df_efficient_frontier (pd.DataFrame): A DataFrame with the portfolios
        that compose the efficient frontier.
        df_portfolios (pd.DataFrame, optional): A DataFrame with the porfolios
        generated by sampling from ansatz. Defaults to None.
    """

    _, ax = plt.subplots()

    ax.set_title("Discrete Efficient Frontier")
    ax.plot(
        df_efficient_frontier.portfolio_risk.values,
        df_efficient_frontier.portfolio_return.values,
        linestyle="--",
        marker="",
        color="black",
        label="Efficient Frontier",
    )
    if not df_portfolios is None:
        sns.scatterplot(
            data=df_portfolios,
            x="portfolio_risk",
            y="portfolio_return",
            hue="sharpe",
            ax=ax,
        )
    ax.set_xlabel("Risk")
    ax.set_ylabel("Return")
    ax.legend(loc=[1,0])

    plt.show()


def plot_interactive_efficient_frontier(
    returns: np.ndarray, risks: np.ndarray, portfolios: list = None
) -> go.Figure:
    """Creates an interactive plot of the efficient
    frontier.
    
    Args:
        returns (np.ndarray): An array with the returns of the
        portfolios that belongs to the efficient frontier.
        risks (np.ndarray): An array with the risks of the porfolios
        that belongs to the efficient frontier.
        portfolios (list, optional): A list with the portfolios 
        to be added in the plot. Defaults to None.
    """

    data = [
        go.Scatter(
            x=risks,
            y=returns,
            mode="markers+lines",
            line=dict(dash="dash"),
            marker=dict(color="black"),
            showlegend=True,
            name="Efficient Frontier",
        )
    ]
    if not portfolios is None:
        data.extend(portfolios)
    fig = go.Figure(data=data)
    fig.update_layout(
        xaxis_title="Risk",
        yaxis_title="Return",
        title_text="Discrete Efficient Frontier",
    )

    return fig
